
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t parvez9809/test-app
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u parvez9809 --password-stdin 
    - run: docker push parvez9809/test-app:latest